In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("Telco_Customer_Churn.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (7043, 21)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
# Check column names
print("Columns:")
print(df.columns.tolist())

# Check data types and missing values
print("\nData Information:")
df.info()

Columns:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
# Check missing values
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
# Basic statistical summary
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,7590-VHVEG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
PhoneService,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultipleLines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InternetService,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineSecurity,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineBackup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DeviceProtection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TechSupport,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7043,6531,,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Check the values that cannot be treated as numbers
total_charges_numeric = pd.to_numeric(df["TotalCharges"], errors="coerce")

print("Non-numeric TotalCharges values:",
      total_charges_numeric.isna().sum())

print("\nRows with non-numeric TotalCharges:")
print(df.loc[total_charges_numeric.isna(), ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]])

Non-numeric TotalCharges values: 11

Rows with non-numeric TotalCharges:
      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

In [7]:
# Check the churn distribution
print(df["Churn"].value_counts())

print("\nChurn percentage:")
print(df["Churn"].value_counts(normalize=True).mul(100).round(2))

Churn
No     5174
Yes    1869
Name: count, dtype: int64

Churn percentage:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [8]:
# Create a clean copy of the dataset
df_clean = df.copy()

# Convert TotalCharges from text to numeric
df_clean["TotalCharges"] = pd.to_numeric(
    df_clean["TotalCharges"],
    errors="coerce"
)

# Fill missing TotalCharges with 0
df_clean["TotalCharges"] = df_clean["TotalCharges"].fillna(0)

# Check the result
print("Missing TotalCharges after cleaning:",
      df_clean["TotalCharges"].isnull().sum())

print("TotalCharges data type:",
      df_clean["TotalCharges"].dtype)

Missing TotalCharges after cleaning: 0
TotalCharges data type: float64

In [9]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [10]:
df_clean.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
# Churn count
churn_count = df_clean["Churn"].value_counts()

print("Customer Churn Count:")
print(churn_count)

# Churn percentage
churn_percentage = (
    df_clean["Churn"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("\nCustomer Churn Percentage:")
print(churn_percentage)

Customer Churn Count:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Customer Churn Percentage:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [12]:
# Key churn KPIs
total_customers = len(df_clean)
churned_customers = (df_clean["Churn"] == "Yes").sum()
retained_customers = (df_clean["Churn"] == "No").sum()
churn_rate = (churned_customers / total_customers) * 100

print("Total Customers:", total_customers)
print("Churned Customers:", churned_customers)
print("Retained Customers:", retained_customers)
print("Churn Rate:", round(churn_rate, 2), "%")

Total Customers: 7043
Churned Customers: 1869
Retained Customers: 5174
Churn Rate: 26.54 %

In [13]:
# Churn by contract type

contract_churn = pd.crosstab(
    df_clean["Contract"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(contract_churn)

Churn              No    Yes
Contract
Month-to-month  57.29  42.71
One year        88.73  11.27
Two year        97.17   2.83

In [14]:
# Customer count by contract and churn status

contract_count = pd.crosstab(
    df_clean["Contract"],
    df_clean["Churn"]
)

print(contract_count)

Churn             No   Yes
Contract
Month-to-month  2220  1655
One year        1307   166
Two year        1647    48

In [15]:
# Create tenure groups

df_clean["TenureGroup"] = pd.cut(
    df_clean["tenure"],
    bins=[-1, 12, 24, 48, 72],
    labels=["0-12 Months", "13-24 Months", "25-48 Months", "49-72 Months"]
)

# Churn rate by tenure group

tenure_churn = pd.crosstab(
    df_clean["TenureGroup"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(tenure_churn)

Churn            No    Yes
TenureGroup
0-12 Months   52.56  47.44
13-24 Months  71.29  28.71
25-48 Months  79.61  20.39
49-72 Months  90.49   9.51

In [16]:
# Customer counts by tenure group and churn

tenure_count = pd.crosstab(
    df_clean["TenureGroup"],
    df_clean["Churn"]
)

print(tenure_count)

Churn           No   Yes
TenureGroup
0-12 Months   1149  1037
13-24 Months   730   294
25-48 Months  1269   325
49-72 Months  2026   213

In [17]:
# Churn by Internet Service

internet_churn = pd.crosstab(
    df_clean["InternetService"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(internet_churn)

Churn               No    Yes
InternetService
DSL              81.04  18.96
Fiber optic      58.11  41.89
No               92.60   7.40

In [18]:
# Customer counts by Internet Service and Churn

internet_count = pd.crosstab(
    df_clean["InternetService"],
    df_clean["Churn"]
)

print(internet_count)

Churn              No   Yes
InternetService
DSL              1962   459
Fiber optic      1799  1297
No               1413   113

In [19]:
# Create monthly charge groups

df_clean["MonthlyChargeGroup"] = pd.qcut(
    df_clean["MonthlyCharges"],
    q=4,
    labels=["Low", "Medium-Low", "Medium-High", "High"]
)

# Churn rate by monthly charge group

charge_churn = pd.crosstab(
    df_clean["MonthlyChargeGroup"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(charge_churn)

Churn                  No    Yes
MonthlyChargeGroup
Low                 88.76  11.24
Medium-Low          75.42  24.58
Medium-High         62.49  37.51
High                67.12  32.88

In [20]:
# Customer counts by monthly charge group

charge_count = pd.crosstab(
    df_clean["MonthlyChargeGroup"],
    df_clean["Churn"]
)

print(charge_count)

Churn                 No  Yes
MonthlyChargeGroup
Low                 1564  198
Medium-Low          1332  434
Medium-High         1098  659
High                1180  578

In [21]:
# Churn rate by payment method

payment_churn = pd.crosstab(
    df_clean["PaymentMethod"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(payment_churn)

Churn                         No    Yes
PaymentMethod
Bank transfer (automatic)  83.29  16.71
Credit card (automatic)    84.76  15.24
Electronic check           54.71  45.29
Mailed check               80.89  19.11

In [22]:
# Churn rate by payment method

payment_churn = pd.crosstab(
    df_clean["PaymentMethod"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(payment_churn)

Churn                         No    Yes
PaymentMethod
Bank transfer (automatic)  83.29  16.71
Credit card (automatic)    84.76  15.24
Electronic check           54.71  45.29
Mailed check               80.89  19.11

In [23]:
# Churn by Online Security

security_churn = pd.crosstab(
    df_clean["OnlineSecurity"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print("Online Security:")
print(security_churn)

Online Security:
Churn                   No    Yes
OnlineSecurity
No                   58.23  41.77
No internet service  92.60   7.40
Yes                  85.39  14.61

In [24]:
# Churn by Tech Support

support_churn = pd.crosstab(
    df_clean["TechSupport"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print("\nTech Support:")
print(support_churn)

Tech Support:
Churn                   No    Yes
TechSupport
No                   58.36  41.64
No internet service  92.60   7.40
Yes                  84.83  15.17

In [25]:
# Churn by Device Protection

device_churn = pd.crosstab(
    df_clean["DeviceProtection"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print("\nDevice Protection:")
print(device_churn)

Device Protection:
Churn                   No    Yes
DeviceProtection
No                   60.87  39.13
No internet service  92.60   7.40
Yes                  77.50  22.50

In [26]:
# Create an analytical customer risk score

df_clean["RiskScore"] = 0

df_clean["RiskScore"] += (
    df_clean["Contract"] == "Month-to-month"
).astype(int)

df_clean["RiskScore"] += (
    df_clean["tenure"] <= 12
).astype(int)

df_clean["RiskScore"] += (
    df_clean["InternetService"] == "Fiber optic"
).astype(int)

df_clean["RiskScore"] += (
    df_clean["PaymentMethod"] == "Electronic check"
).astype(int)

df_clean["RiskScore"] += (
    df_clean["OnlineSecurity"] == "No"
).astype(int)

df_clean["RiskScore"] += (
    df_clean["TechSupport"] == "No"
).astype(int)

# Convert score into risk category
df_clean["RiskCategory"] = pd.cut(
    df_clean["RiskScore"],
    bins=[-1, 1, 3, 6],
    labels=["Low Risk", "Medium Risk", "High Risk"]
)

print(df_clean[["customerID", "RiskScore", "RiskCategory", "Churn"]].head(10))

   customerID  RiskScore RiskCategory Churn
0  7590-VHVEG          5    High Risk    No
1  5575-GNVDE          1     Low Risk    No
2  3668-QPYBK          3  Medium Risk   Yes
3  7795-CFOCW          0     Low Risk    No
4  9237-HQITU          6    High Risk   Yes
5  9305-CDSKC          6    High Risk   Yes
6  1452-KIOVK          4    High Risk    No
7  6713-OKOMC          3  Medium Risk    No
8  7892-POOKP          4    High Risk   Yes
9  6388-TABGU          1     Low Risk    No

In [27]:
# Risk category distribution

risk_summary = pd.crosstab(
    df_clean["RiskCategory"],
    df_clean["Churn"],
    normalize="index"
).mul(100).round(2)

print(risk_summary)

Churn            No    Yes
RiskCategory
Low Risk      96.24   3.76
Medium Risk   81.45  18.55
High Risk     46.05  53.95

In [28]:
# Create verified business metrics for our AI analyst

ai_summary = {
    "total_customers": len(df_clean),
    "churned_customers": (df_clean["Churn"] == "Yes").sum(),
    "overall_churn_rate": round(
        (df_clean["Churn"] == "Yes").mean() * 100, 2
    ),
    "month_to_month_churn_rate": 42.71,
    "one_year_churn_rate": 11.27,
    "two_year_churn_rate": 2.84,
    "new_customer_0_12_month_churn_rate": 47.44,
    "fiber_optic_churn_rate": 41.89,
    "electronic_check_churn_rate": 45.29,
    "high_risk_churn_rate": 53.95,
    "medium_risk_churn_rate": 18.55,
    "low_risk_churn_rate": 3.76
}

ai_summary

{'total_customers': 7043,
 'churned_customers': np.int64(1869),
 'overall_churn_rate': np.float64(26.54),
 'month_to_month_churn_rate': 42.71,
 'one_year_churn_rate': 11.27,
 'two_year_churn_rate': 2.84,
 'new_customer_0_12_month_churn_rate': 47.44,
 'fiber_optic_churn_rate': 41.89,
 'electronic_check_churn_rate': 45.29,
 'high_risk_churn_rate': 53.95,
 'medium_risk_churn_rate': 18.55,
 'low_risk_churn_rate': 3.76}

In [29]:
import sqlite3

# Create a local SQLite database
conn = sqlite3.connect("customer_churn.db")

# Load the cleaned dataset into a SQL table
df_clean.to_sql(
    "customer_churn",
    conn,
    if_exists="replace",
    index=False
)

print("SQL database created successfully!")
print("Table: customer_churn")

SQL database created successfully!
Table: customer_churn

In [30]:
query = """
SELECT
    Churn,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM customer_churn), 2) AS percentage
FROM customer_churn
GROUP BY Churn;
"""

result = pd.read_sql_query(query, conn)
result

  Churn  customer_count  percentage
0    No            5174       73.46
1   Yes            1869       26.54

In [31]:
query = """
SELECT
    Contract,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY Contract
ORDER BY churn_rate DESC;
"""

result = pd.read_sql_query(query, conn)
result

         Contract  total_customers  churned_customers  churn_rate
0  Month-to-month             3875               1655       42.71
1        One year             1473                166       11.27
2        Two year             1695                 48        2.83

In [32]:
query = """
SELECT
    CASE
        WHEN tenure <= 12 THEN '0-12 Months'
        WHEN tenure <= 24 THEN '13-24 Months'
        WHEN tenure <= 48 THEN '25-48 Months'
        ELSE '49-72 Months'
    END AS tenure_group,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY tenure_group
ORDER BY
    CASE tenure_group
        WHEN '0-12 Months' THEN 1
        WHEN '13-24 Months' THEN 2
        WHEN '25-48 Months' THEN 3
        WHEN '49-72 Months' THEN 4
    END;
"""

result = pd.read_sql_query(query, conn)
result

   tenure_group  total_customers  churned_customers  churn_rate
0   0-12 Months             2186               1037       47.44
1  13-24 Months             1024                294       28.71
2  25-48 Months             1594                325       20.39
3  49-72 Months             2239                213        9.51

In [33]:
query = """
SELECT
    PaymentMethod,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY PaymentMethod
ORDER BY churn_rate DESC;
"""

result = pd.read_sql_query(query, conn)
result

               PaymentMethod  total_customers  churned_customers  churn_rate
0           Electronic check             2365               1071       45.29
1               Mailed check             1612                308       19.11
2  Bank transfer (automatic)             1544                258       16.71
3    Credit card (automatic)             1522                232       15.24

In [34]:
query = """
SELECT
    InternetService,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY InternetService
ORDER BY churn_rate DESC;
"""

result = pd.read_sql_query(query, conn)
result

  InternetService  total_customers  churned_customers  churn_rate
0     Fiber optic             3096               1297       41.89
1             DSL             2421                459       18.96
2              No             1526                113        7.40

In [35]:
query = """
SELECT
    OnlineSecurity,
    TechSupport,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM customer_churn
GROUP BY OnlineSecurity, TechSupport
ORDER BY churn_rate DESC;
"""

result = pd.read_sql_query(query, conn)
result

,OnlineSecurity,TechSupport,total_customers,churned_customers,churn_rate
0,No,No,2553,1250,48.96
1,No,Yes,945,211,22.33
2,Yes,No,920,196,21.30
3,Yes,Yes,1099,99,9.01
4,No internet service,No internet service,1526,113,7.40

In [36]:
query = """
WITH risk_scored AS (
    SELECT
        CustomerID,
        Churn,
        (
            CASE WHEN Contract = 'Month-to-month' THEN 1 ELSE 0 END
            +
            CASE WHEN tenure <= 12 THEN 1 ELSE 0 END
            +
            CASE WHEN InternetService = 'Fiber optic' THEN 1 ELSE 0 END
            +
            CASE WHEN PaymentMethod = 'Electronic check' THEN 1 ELSE 0 END
            +
            CASE WHEN OnlineSecurity = 'No' THEN 1 ELSE 0 END
            +
            CASE WHEN TechSupport = 'No' THEN 1 ELSE 0 END
        ) AS risk_score
    FROM customer_churn
)

SELECT
    CASE
        WHEN risk_score <= 1 THEN 'Low Risk'
        WHEN risk_score <= 3 THEN 'Medium Risk'
        ELSE 'High Risk'
    END AS risk_category,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) AS churned_customers,
    ROUND(
        SUM(CASE WHEN Churn = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*),
        2
    ) AS churn_rate
FROM risk_scored
GROUP BY risk_category
ORDER BY
    CASE risk_category
        WHEN 'Low Risk' THEN 1
        WHEN 'Medium Risk' THEN 2
        WHEN 'High Risk' THEN 3
    END;
"""

result = pd.read_sql_query(query, conn)
result

  risk_category  total_customers  churned_customers  churn_rate
0      Low Risk             2341                 88        3.76
1   Medium Risk             2135                396       18.55
2     High Risk             2567               1385       53.95

In [37]:
ai_analyst_summary = {
    "overall": {
        "total_customers": 7043,
        "churned_customers": 1869,
        "churn_rate": 26.54
    },
    "contract": {
        "month_to_month": 42.71,
        "one_year": 11.27,
        "two_year": 2.83
    },
    "tenure": {
        "0_12_months": 47.44,
        "13_24_months": 28.71,
        "25_48_months": 20.39,
        "49_72_months": 9.51
    },
    "payment": {
        "electronic_check": 45.29,
        "mailed_check": 19.11,
        "bank_transfer_automatic": 16.71,
        "credit_card_automatic": 15.24
    },
    "internet_service": {
        "fiber_optic": 41.89,
        "dsl": 18.96,
        "no_internet_service": 7.40
    },
    "support_services": {
        "no_security_no_support": 48.96,
        "no_security_with_support": 22.33,
        "security_without_support": 21.30,
        "security_and_support": 9.01
    },
    "risk": {
        "low": 3.76,
        "medium": 18.55,
        "high": 53.95
    }
}

print("Verified AI Analyst dataset created successfully!")

Verified AI Analyst dataset created successfully!

In [38]:
ai_analyst_prompt = f"""
You are a senior Data Analyst reviewing a verified customer churn analysis.

Use ONLY the verified metrics below. Do not invent statistics.

VERIFIED METRICS:
{ai_analyst_summary}

TASK:
Create a concise business analysis with these sections:

1. KEY FINDINGS
Identify the most important observed churn patterns.

2. POSSIBLE EXPLANATIONS
Suggest reasonable hypotheses, but clearly label them as hypotheses.
Do not claim correlation proves causation.

3. RECOMMENDED ACTIONS
Suggest 4 practical customer-retention actions based only on the available data.

4. HIGH-RISK CUSTOMER PROFILE
Describe the characteristics represented in the rule-based High Risk group.

5. DATA LIMITATIONS
Explain important limitations of this analysis.

IMPORTANT:
- Use exact percentages from the verified metrics.
- Do not create new statistics.
- Do not call the risk score an ML prediction.
- The risk score is a transparent rule-based business scoring system.
- Keep facts separate from hypotheses.
"""

print(ai_analyst_prompt)

You are a senior Data Analyst reviewing a verified customer churn analysis.

Use ONLY the verified metrics below. Do not invent statistics.

VERIFIED METRICS:
{'overall': {'total_customers': 7043, 'churned_customers': 1869, 'churn_rate': 26.54}, 'contract': {'month_to_month': 42.71, 'one_year': 11.27, 'two_year': 2.83}, 'tenure': {'0_12_months': 47.44, '13_24_months': 28.71, '25_48_months': 20.39, '49_72_months': 9.51}, 'payment': {'electronic_check': 45.29, 'mailed_check': 19.11, 'bank_transfer_automatic': 16.71, 'credit_card_automatic': 15.24}, 'internet_service': {'fiber_optic': 41.89, 'dsl': 18.96, 'no_internet_service': 7.4}, 'support_services': {'no_security_no_support': 48.96, 'no_security_with_support': 22.33, 'security_without_support': 21.3, 'security_and_support': 9.01}, 'risk': {'low': 3.76, 'medium': 18.55, 'high': 53.95}}

TASK:
Create a concise business analysis with these sections:

1. KEY FINDINGS
Identify the most important observed churn patterns.

2. POSSIBLE EXPLANATIONS
Suggest reasonable hypotheses, but clearly label them as hypotheses.
Do not claim correlation proves causation.

3. RECOMMENDED ACTIONS
Suggest 4 practical customer-retention actions based only on the available data.

4. HIGH-RISK CUSTOMER PROFILE
Describe the characteristics represented in the rule-based High Risk group.

5. DATA LIMITATIONS
Explain important limitations of this analysis.

IMPORTANT:
- Use exact percentages from the verified metrics.
- Do not create new statistics.
- Do not call the risk score an ML prediction.
- The risk score is a transparent rule-based business scoring system.
- Keep facts separate from hypotheses.

In [39]:
# Export cleaned customer churn data for Power BI
df_clean.to_csv("Customer_Churn_Cleaned.csv", index=False)

print("Power BI file created successfully!")
print("File: Customer_Churn_Cleaned.csv")

Power BI file created successfully!
File: Customer_Churn_Cleaned.csv